[project]
name = "chef-package-manager"
description = "Security-focused utility for installing software for macOS & Linux."

dynamic = ["version"]

authors = [
    { name = "Axel H. Karlsson", email = "git@axelkarlsson.se" }
]

requires-python = ">= 3.14"

dependencies = [
    "build>=1.4.4",
    "requests>=2.34.2",
]

[project.scripts]
chef = "chef:main.main"

[build-system]
requires = ["setuptools >= 82.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "chef.__init__.__version__"}
